# Generated by Django 5.2.3 on 2025-06-13 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_garden_latitude_alter_garden_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 13, 21, 24, 25, 748264, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
